-- Drop data tables only (metadata tables are owned by the extension)
DROP TABLE IF EXISTS call_center CASCADE;
DROP TABLE IF EXISTS catalog_page CASCADE;
DROP TABLE IF EXISTS catalog_returns CASCADE;
DROP TABLE IF EXISTS catalog_sales CASCADE;
DROP TABLE IF EXISTS customer CASCADE;
DROP TABLE IF EXISTS customer_address CASCADE;
DROP TABLE IF EXISTS customer_demographics CASCADE;
DROP TABLE IF EXISTS date_dim CASCADE;
DROP TABLE IF EXISTS household_demographics CASCADE;
DROP TABLE IF EXISTS income_band CASCADE;
DROP TABLE IF EXISTS inventory CASCADE;
DROP TABLE IF EXISTS item CASCADE;
DROP TABLE IF EXISTS promotion CASCADE;
DROP TABLE IF EXISTS reason CASCADE;
DROP TABLE IF EXISTS ship_mode CASCADE;
DROP TABLE IF EXISTS store CASCADE;
DROP TABLE IF EXISTS store_returns CASCADE;
DROP TABLE IF EXISTS store_sales CASCADE;
DROP TABLE IF EXISTS time_dim CASCADE;
DROP TABLE IF EXISTS warehouse CASCADE;
DROP TABLE IF EXISTS web_page CASCADE;
DROP TABLE IF EXISTS web_returns CASCADE;
DROP TABLE IF EXISTS web_sales CASCADE;
DROP TABLE IF EXISTS web_site CASCADE;
-- Clear query stats when switching distribution
TRUNCATE tpcds.tpcds_query_stats;
